### ISSUE TITLE
Proje Görev Dağılımı ve Bitiş Tarihi Planlaması

### ISSUE THREAD

**Issue by hakankgn** [BilgeAdam-Academy-Students-3507/graduation-project#16]
Merhaba herkese,

İssueyu, projemizin görev dağılımını ve planlanan bitiş tarihini belirlemek için açıyorum. Lütfen herkes kendi üzerine düşen görevleri dikkatlice incelesin ve sürecin nasıl işleyeceği hakkında fikirlerini paylaşsın. Ayrıca, herhangi bir sorunuz veya öneriniz varsa, bu issue altında tartışabiliriz.

**Planlanan Bitiş Tarihi:** *En geç 22 Ocak 2024*

**Görev Dağılımları:**
1. **Musa - Kevin:**
   - Card tasarımı
   - Renk seçimi ve tipografi
   - Carousel ve fotoğraf entegrasyonu

2. **Seray - Şeyma:**
   - Responsive Design

3. **Hakan:**
   - Typescript dönüşümü

4. **Dökümantasyon Oluşturma:**
   - Musa
   - Kevin
   - Seray
   - Şeyma
   - Hakan

Herhangi bir zorluk yaşarsanız, lütfen zamanında iletişime geçin.

İyi çalışmalar

**Comment by hakankgn** [comment]
Projeye kaldığı yerden devam edip görev üstlenmek isteyen olur ise whatsappdan Kevin ile iletişime geçebilir.

**Comment by Kev-BB** [comment]
@dncmusa ile verilen görevi yerine getireceğiz.

**Comment by seraykursunel** [comment]
Şeyma ile birlikte projenin responsive design aşamasını düzenleyeceğiz.
