### ISSUE TITLE
Carousel Component

### ISSUE THREAD

**Issue by Kev-BB** [BilgeAdam-Academy-Students-3507/graduation-project#3]
Projemiz için aşağıda verilen örnekte ki gibi bir carousel component’a ihtiyacımız var.

![Carousel](https://github.com/BilgeAdam-Academy-Students-3507/graduation-project/assets/118001660/5ec91039-df7b-4a10-8cca-3909217baf0b)

**Comment by dncmusa** [comment]
carousel component halledildi. pull request açıldı.
