### ISSUE TITLE
Card Component 

### ISSUE THREAD

**Issue by dncmusa** [BilgeAdam-Academy-Students-3507/graduation-project#4]
Projemizde örneğe benzer bir Card component’a ihtiyacımız var. Bu component üzerinde kim çalışmak ister?

![Resim1](https://github.com/BilgeAdam-Academy-Students-3507/graduation-project/assets/108437114/8f381b69-9d44-4491-94d2-61021cfc900f)

**Comment by irfanbariss** [comment]
Card component temelleri oluşturuldu
