### ISSUE TITLE
Light/Dark Mode Toogler

### ISSUE THREAD

**Issue by seraykursunel** [BilgeAdam-Academy-Students-3507/graduation-project#5]
Projemizde örneğe benzer bir Theme Toggler’a  ihtiyacımız var. Bu component’ı kim oluşturmak ister?
![image](https://github.com/BilgeAdam-Academy-Students-3507/graduation-project/assets/120279034/a008cd4b-5664-48d8-a908-dc430fa53c59)

**Comment by hakankgn** [comment]
Theme Toggler'ı oluşturma görevini üstleniyorum. Temel fonksiyonelliği ben yazacağım ve `styled-components` kullanarak @bseymad ile birlikte CSS tarafını planlayacağım. 👨‍💻

**Comment by hakankgn** [comment]
Theme Toggler'ı oluşturma görevini üstleniyorum. Temel fonksiyonelliği ben yazacağım ve `styled-components` kullanarak @bseymad ile birlikte CSS tarafını planlayacağım. 👨‍💻
